name: example_auth
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  # Firebase
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  google_sign_in: 7.2.0
  firebase_database: ^12.1.2
  firebase_storage: ^13.0.6
  cloud_functions: ^6.0.6
  firebase_analytics: ^12.1.1
  firebase_crashlytics: ^5.0.7
  firebase_ui_firestore: ^2.0.1
  google_fonts: ^8.0.0
  simple_gravatar: ^1.1.0 # Provides Auth default images.

  # Core Flutter
  universal_io: ^2.3.1
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.4
  logging: ^1.3.0

  # 1st Party Core Framework
  navigation_utils:
    path: ../

  # 3rd Party Core Framework
  get_it: ^9.2.0
  equatable: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.11.4
  build_runner: ^2.10.5

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/